# SimplerLLM - Simplified interface for LLMs and Voice APIs

# Language module exports
from .language import (
    LLM,
    LLMProvider,
    ReliableLLM,
    OpenAILLM,
    GeminiLLM,
    AnthropicLLM,
    OllamaLLM,
    DeepSeekLLM,
    MiniAgent,
    StepResult,
    FlowResult,
    LLMJudge,
    JudgeMode,
    JudgeResult,
    ProviderResponse,
    ProviderEvaluation,
    EvaluationReport,
    LLMFeedbackLoop,
    FeedbackResult,
    IterationResult,
    Critique,
    LLMProviderRouter,
    ProviderConfig,
    RoutingResult,
    QueryClassification,
    LLMClusterer,
    Cluster,
    ClusterMetadata,
    ChunkReference,
    ClusterTree,
    ClusteringResult,
    ClusteringConfig,
    TreeConfig,
    save_clustering_result,
    load_clustering_result,
    save_cluster_tree,
    load_cluster_tree,
    get_clustering_stats,
    LLMRetriever,
    RetrievalResult,
    HierarchicalRetrievalResponse,
    RetrievalConfig,
    GuardrailsLLM,
    GuardrailAction,
    GuardrailResult,
    InputGuardrail,
    OutputGuardrail,
    CompositeGuardrail,
    GuardrailException,
    GuardrailBlockedException,
    GuardrailValidationException,
    GuardrailConfigurationException,
    GuardrailTimeoutException,
    PromptInjectionGuardrail,
    TopicFilterGuardrail,
    InputPIIDetectionGuardrail,
    FormatValidatorGuardrail,
    OutputPIIDetectionGuardrail,
    ContentSafetyGuardrail,
    LengthValidatorGuardrail,
)

# Voice module exports
from .voice import (
    TTS,
    TTSProvider,
    OpenAITTS,
    ElevenLabsTTS,
    TTSFullResponse,
    STT,
    STTProvider,
    OpenAISTT,
    STTFullResponse,
    VoiceChat,
    VoiceChatConfig,
    ConversationMessage,
    ConversationRole,
    VoiceTurnResult,
    VoiceChatSession,
    ConversationManager,
    LiveVoiceChatConfig,
    _LIVE_VOICE_AVAILABLE,
    DialogueGenerator,
    Dialogue,
    DialogueLine,
    SpeakerConfig,
    DialogueGenerationConfig,
    AudioDialogueResult,
    DialogueStyle,
    VideoTranscriber,
    MultiLanguageCaptionGenerator,
    VideoTranscriptionResult,
    CaptionSegment,
    LanguageCaptions,
    MultiLanguageCaptionsResult,
    VideoDubber,
    DubbedSegment,
    DubbingConfig,
    VideoDubbingResult,
    RealtimeVoice,
    RealtimeVoiceProvider,
    RealtimeSessionConfig,
    OpenAIRealtimeVoice,
    TurnDetectionType,
    Voice,
    AudioFormat,
    Modality,
    RealtimeVoiceChat,
    RealtimeVoiceChatConfig,
)

# LiveVoiceChat requires PortAudio - import conditionally
if _LIVE_VOICE_AVAILABLE:
    from .voice import LiveVoiceChat, AudioRecorder, AudioPlayer
else:
    LiveVoiceChat = None
    AudioRecorder = None
    AudioPlayer = None

# Image module exports
from .image import (
    ImageGenerator,
    ImageProvider,
    ImageSize,
    OpenAIImageGenerator,
    StabilityImageGenerator,
    GoogleImageGenerator,
    ImageGenerationResponse,
)

__all__ = [
    # Language module
    'LLM',
    'LLMProvider',
    'ReliableLLM',
    'OpenAILLM',
    'GeminiLLM',
    'AnthropicLLM',
    'OllamaLLM',
    'DeepSeekLLM',
    'MiniAgent',
    'StepResult',
    'FlowResult',
    'LLMJudge',
    'JudgeMode',
    'JudgeResult',
    'ProviderResponse',
    'ProviderEvaluation',
    'EvaluationReport',
    'LLMFeedbackLoop',
    'FeedbackResult',
    'IterationResult',
    'Critique',
    'LLMProviderRouter',
    'ProviderConfig',
    'RoutingResult',
    'QueryClassification',
    'LLMClusterer',
    'Cluster',
    'ClusterMetadata',
    'ChunkReference',
    'ClusterTree',
    'ClusteringResult',
    'ClusteringConfig',
    'TreeConfig',
    'save_clustering_result',
    'load_clustering_result',
    'save_cluster_tree',
    'load_cluster_tree',
    'get_clustering_stats',
    'LLMRetriever',
    'RetrievalResult',
    'HierarchicalRetrievalResponse',
    'RetrievalConfig',
    # Guardrails
    'GuardrailsLLM',
    'GuardrailAction',
    'GuardrailResult',
    'InputGuardrail',
    'OutputGuardrail',
    'CompositeGuardrail',
    'GuardrailException',
    'GuardrailBlockedException',
    'GuardrailValidationException',
    'GuardrailConfigurationException',
    'GuardrailTimeoutException',
    'PromptInjectionGuardrail',
    'TopicFilterGuardrail',
    'InputPIIDetectionGuardrail',
    'FormatValidatorGuardrail',
    'OutputPIIDetectionGuardrail',
    'ContentSafetyGuardrail',
    'LengthValidatorGuardrail',
    # Voice module - TTS
    'TTS',
    'TTSProvider',
    'OpenAITTS',
    'ElevenLabsTTS',
    'TTSFullResponse',
    # Voice module - STT
    'STT',
    'STTProvider',
    'OpenAISTT',
    'STTFullResponse',
    # Voice module - VoiceChat
    'VoiceChat',
    'VoiceChatConfig',
    'ConversationMessage',
    'ConversationRole',
    'VoiceTurnResult',
    'VoiceChatSession',
    'ConversationManager',
    # Voice module - LiveVoiceChat (config always available, others require PortAudio)
    'LiveVoiceChatConfig',
    # Voice module - Dialogue
    'DialogueGenerator',
    'Dialogue',
    'DialogueLine',
    'SpeakerConfig',
    'DialogueGenerationConfig',
    'AudioDialogueResult',
    'DialogueStyle',
    # Voice module - Video Transcription
    'VideoTranscriber',
    'MultiLanguageCaptionGenerator',
    'VideoTranscriptionResult',
    'CaptionSegment',
    'LanguageCaptions',
    'MultiLanguageCaptionsResult',
    # Voice module - Video Dubbing
    'VideoDubber',
    'DubbedSegment',
    'DubbingConfig',
    'VideoDubbingResult',
    # Voice module - Realtime Voice
    'RealtimeVoice',
    'RealtimeVoiceProvider',
    'RealtimeSessionConfig',
    'OpenAIRealtimeVoice',
    'TurnDetectionType',
    'Voice',
    'AudioFormat',
    'Modality',
    'RealtimeVoiceChat',
    'RealtimeVoiceChatConfig',
    # Image module
    'ImageGenerator',
    'ImageProvider',
    'ImageSize',
    'OpenAIImageGenerator',
    'StabilityImageGenerator',
    'GoogleImageGenerator',
    'ImageGenerationResponse',
]

# Conditionally add LiveVoiceChat exports if PortAudio is available
if _LIVE_VOICE_AVAILABLE:
    __all__.extend(['LiveVoiceChat', 'AudioRecorder', 'AudioPlayer'])
